### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by SergeyRyskin** [atiilla/woopy#1]
Hi! When I try to create a new docker-compose.yml from Swagger UI (http://127.0.0.1:5000/api/), I get a CORS error.
<img width="1391" alt="Screenshot 2024-02-03 at 15 09 26" src="https://github.com/atiilla/woopy/assets/61845734/5b7de7be-b649-406e-afae-f12421e12745">
But in console where I run my local server (WooPyAPI) I dont have any error.
![Screenshot 2024-02-03 at 15 09 53](https://github.com/atiilla/woopy/assets/61845734/84e51065-e1c1-4ee6-9cc8-78b9dc59fcd1)
At first, I thought the error was caused by me, or my .env file I had generated, but later I generated a new mock .env and faced the same problem again. Here you can find the .env that I generated using web.py as a reference. P.S: Same file used in Swagger 

``` 
#Database Configuration
DATABASE_NAME=pizzify_db
DATABASE_USER=pizzify_user
DATABASE_HOST=localhost
# Mail Configuration
MAIL_SMTP_HOST=smtp.example.com
MAIL_SMTP_USER=pizzify@example.com
# Cache Configuration
CACHE_HOST=localhost
CACHE_PORT=6379
# Website Configuration
WEBSITE_TITLE=Ja Pizzify
WEBSITE_HOSTNAME=japizzify.com
WEBSITE_ADMIN_USERNAME=admin
WEBSITE_ADMIN_EMAIL=admin@japizzify.com
# Proxy Configuration
PROXY_TITLE=JaPizzifyProxy
PROXY_HOSTNAME=japizzify-proxy.com
# Host Configuration
HOST_HOSTNAME=ja-pizzify-server
HOST_IP=192.168.1.100
HOST_MAC=00:11:22:33:44:55
HOST_CPU=4
HOST_RAM=8GB
HOST_OS=Linux
HOST_KERNEL=4.19.0
HOST_DOCKER=20.10.3
``` 

Since nothing was working with the web part, I wanted to experiment with the CLI and followed this path: 
1-) I created a test file within the project (Root Directory).
2-) I created an .env file in the test file.
And as a result, my file impression was like this:
``` VSProjects/woopy/test/.env``` 

Then I run command witch has written in README.md
I wrote the generate command: 
``` python -m cli gen-dc test``` 
But as a result, I kept getting errors again.
![Screenshot 2024-02-03 at 15 43 44](https://github.com/atiilla/woopy/assets/61845734/1ca59efc-e0d6-4c93-a02b-35dc79063b9c)

Thank you!

**Comment by SergeyRyskin** [comment]
BTW: After typing the `python3 -m web` command, the terminal sends us to `localhost:5000`, but by default Flask does not run on `localhost`, it starts at `port 127.0.0.1/`. I am sharing with you the article link that may be helpful to fix this.

[How to change start port in flask?](https://copyprogramming.com/howto/unable-to-get-flask-app-running-on-127-0-0-1)

**Comment by atiilla** [comment]
issue has been resolved
